### ISSUE TITLE
remove taxes for included in price

### ISSUE THREAD

**Issue by t-n-y** [gewebe/SyliusVATPlugin#3]
Hi,

I tried the plugin, and i was wondering if it is possible to make it work for the included taxes. It works for non included taxes (removes the taxes depending of which country i select), but not for included taxes.

Is it normal or maybe i am doing something wrong.

Thank you for your help

**Comment by gewebe** [comment]
Hi @t-n-y,

thanks for reporting this issue.

It would be great to reproduce this behavior and extend the [tax total checkout](https://github.com/gewebe/SyliusVATPlugin/blob/master/features/checkout/seeing_tax_total_dependent_on_country_and_vat.feature) test or create a similar one before implementing this feature.

**Comment by gewebe** [comment]
@t-n-y you can update to package version v1.3.1 and included VAT will be deducted from order items and shipping fees. There may be errors in special situations, for example promotions have not been tested yet.
