### ISSUE TITLE
Doctrine mapping with PHP Attributes

### ISSUE THREAD

**Issue by dsbe-ak** [gewebe/SyliusVATPlugin#5]
I'm currently updating my shop to use PHP attributes for the doctrine mapping and this plugin doesn't seem to support them yet.
Any plans in supporting doctrine mapping via PHP attributes (instead of annotations)?

Thanks!

**Comment by gewebe** [comment]
@dsbe-ak thanks for reporting this issue.
You can now upgrade to package version v1.4.1 and also use PHP attributes for doctrine mappings with this plugin.

**Comment by dsbe-ak** [comment]
Thank you very much!
